In [1]:
import numpy as np

In [2]:
def suma_filacolumnas(tabla):
    print ("Suma filas: "+str(np.apply_along_axis(sum, 0, tabla)))
    print ("Suma columnas: "+str(np.apply_along_axis(sum, 1, tabla)))

In [3]:
tabla = np.random.randint(0,10,(3,3))
print (tabla)


[[6 3 2]
 [8 0 3]
 [4 6 2]]


In [4]:
suma_filacolumnas(tabla)

Suma filas: [18  9  7]
Suma columnas: [11 11 12]
