In [1]:
import numpy as np

In [2]:
def cuadrado (rango):
    return (np.random.randint(0, 100, (rango, rango)))

In [3]:
cuadrado (1)

array([[47]])

In [4]:
cuadrado(2)

array([[43, 16],
       [ 7, 34]])

In [5]:
cuadrado (3)

array([[24, 87, 45],
       [22, 49, 11],
       [34, 70,  9]])